import type { Question } from './types';

export const questionBank: Question[] = [
  // ─── same_denominator (8 questions) ───
  {
    id: 'sd-1',
    a: { n: 3, d: 7 },
    b: { n: 5, d: 7 },
    correctChoice: 'B',
    category: 'same_denominator',
    difficulty: 1,
  },
  {
    id: 'sd-2',
    a: { n: 4, d: 9 },
    b: { n: 2, d: 9 },
    correctChoice: 'A',
    category: 'same_denominator',
    difficulty: 1,
  },
  {
    id: 'sd-3',
    a: { n: 1, d: 5 },
    b: { n: 3, d: 5 },
    correctChoice: 'B',
    category: 'same_denominator',
    difficulty: 1,
  },
  {
    id: 'sd-4',
    a: { n: 7, d: 10 },
    b: { n: 3, d: 10 },
    correctChoice: 'A',
    category: 'same_denominator',
    difficulty: 2,
  },
  {
    id: 'sd-5',
    a: { n: 5, d: 12 },
    b: { n: 8, d: 12 },
    correctChoice: 'B',
    category: 'same_denominator',
    difficulty: 2,
  },
  {
    id: 'sd-6',
    a: { n: 11, d: 15 },
    b: { n: 7, d: 15 },
    correctChoice: 'A',
    category: 'same_denominator',
    difficulty: 2,
  },
  {
    id: 'sd-7',
    a: { n: 13, d: 20 },
    b: { n: 17, d: 20 },
    correctChoice: 'B',
    category: 'same_denominator',
    difficulty: 3,
  },
  {
    id: 'sd-8',
    a: { n: 9, d: 16 },
    b: { n: 5, d: 16 },
    correctChoice: 'A',
    category: 'same_denominator',
    difficulty: 3,
  },

  // ─── same_numerator (8 questions) ───
  {
    id: 'sn-1',
    a: { n: 3, d: 5 },
    b: { n: 3, d: 8 },
    correctChoice: 'A',
    category: 'same_numerator',
    difficulty: 1,
  },
  {
    id: 'sn-2',
    a: { n: 2, d: 7 },
    b: { n: 2, d: 3 },
    correctChoice: 'B',
    category: 'same_numerator',
    difficulty: 1,
  },
  {
    id: 'sn-3',
    a: { n: 1, d: 4 },
    b: { n: 1, d: 6 },
    correctChoice: 'A',
    category: 'same_numerator',
    difficulty: 1,
  },
  {
    id: 'sn-4',
    a: { n: 5, d: 9 },
    b: { n: 5, d: 12 },
    correctChoice: 'A',
    category: 'same_numerator',
    difficulty: 2,
  },
  {
    id: 'sn-5',
    a: { n: 4, d: 11 },
    b: { n: 4, d: 7 },
    correctChoice: 'B',
    category: 'same_numerator',
    difficulty: 2,
  },
  {
    id: 'sn-6',
    a: { n: 7, d: 15 },
    b: { n: 7, d: 10 },
    correctChoice: 'B',
    category: 'same_numerator',
    difficulty: 2,
  },
  {
    id: 'sn-7',
    a: { n: 6, d: 13 },
    b: { n: 6, d: 17 },
    correctChoice: 'A',
    category: 'same_numerator',
    difficulty: 3,
  },
  {
    id: 'sn-8',
    a: { n: 8, d: 19 },
    b: { n: 8, d: 11 },
    correctChoice: 'B',
    category: 'same_numerator',
    difficulty: 3,
  },

  // ─── benchmark_half (8 questions) ───
  {
    id: 'bh-1',
    a: { n: 2, d: 5 },
    b: { n: 3, d: 4 },
    correctChoice: 'B',
    category: 'benchmark_half',
    difficulty: 1,
    visual: { type: 'number_line', marks: [0, 0.5, 1], highlight: 0.5 },
  },
  {
    id: 'bh-2',
    a: { n: 5, d: 8 },
    b: { n: 1, d: 3 },
    correctChoice: 'A',
    category: 'benchmark_half',
    difficulty: 1,
    visual: { type: 'number_line', marks: [0, 0.5, 1], highlight: 0.5 },
  },
  {
    id: 'bh-3',
    a: { n: 3, d: 7 },
    b: { n: 4, d: 5 },
    correctChoice: 'B',
    category: 'benchmark_half',
    difficulty: 1,
    visual: { type: 'number_line', marks: [0, 0.5, 1], highlight: 0.5 },
  },
  {
    id: 'bh-4',
    a: { n: 4, d: 9 },
    b: { n: 5, d: 8 },
    correctChoice: 'B',
    category: 'benchmark_half',
    difficulty: 2,
    visual: { type: 'number_line', marks: [0, 0.5, 1], highlight: 0.5 },
  },
  {
    id: 'bh-5',
    a: { n: 7, d: 12 },
    b: { n: 3, d: 8 },
    correctChoice: 'A',
    category: 'benchmark_half',
    difficulty: 2,
    visual: { type: 'number_line', marks: [0, 0.5, 1], highlight: 0.5 },
  },
  {
    id: 'bh-6',
    a: { n: 5, d: 11 },
    b: { n: 7, d: 10 },
    correctChoice: 'B',
    category: 'benchmark_half',
    difficulty: 2,
    visual: { type: 'number_line', marks: [0, 0.5, 1], highlight: 0.5 },
  },
  {
    id: 'bh-7',
    a: { n: 9, d: 16 },
    b: { n: 5, d: 9 },
    correctChoice: 'A',
    category: 'benchmark_half',
    difficulty: 3,
    visual: { type: 'number_line', marks: [0, 0.5, 1], highlight: 0.5 },
  },
  {
    id: 'bh-8',
    a: { n: 6, d: 11 },
    b: { n: 8, d: 15 },
    correctChoice: 'A',
    category: 'benchmark_half',
    difficulty: 3,
    visual: { type: 'number_line', marks: [0, 0.5, 1], highlight: 0.5 },
  },

  // ─── unlike_denominator (8 questions) ───
  {
    id: 'ud-1',
    a: { n: 2, d: 3 },
    b: { n: 3, d: 5 },
    correctChoice: 'A',
    category: 'unlike_denominator',
    difficulty: 1,
  },
  {
    id: 'ud-2',
    a: { n: 1, d: 4 },
    b: { n: 2, d: 5 },
    correctChoice: 'B',
    category: 'unlike_denominator',
    difficulty: 1,
  },
  {
    id: 'ud-3',
    a: { n: 3, d: 4 },
    b: { n: 2, d: 3 },
    correctChoice: 'A',
    category: 'unlike_denominator',
    difficulty: 1,
  },
  {
    id: 'ud-4',
    a: { n: 5, d: 6 },
    b: { n: 7, d: 9 },
    correctChoice: 'A',
    category: 'unlike_denominator',
    difficulty: 2,
  },
  {
    id: 'ud-5',
    a: { n: 4, d: 7 },
    b: { n: 5, d: 8 },
    correctChoice: 'B',
    category: 'unlike_denominator',
    difficulty: 2,
  },
  {
    id: 'ud-6',
    a: { n: 3, d: 10 },
    b: { n: 2, d: 7 },
    correctChoice: 'A',
    category: 'unlike_denominator',
    difficulty: 2,
  },
  {
    id: 'ud-7',
    a: { n: 7, d: 11 },
    b: { n: 5, d: 8 },
    correctChoice: 'A',
    category: 'unlike_denominator',
    difficulty: 3,
  },
  {
    id: 'ud-8',
    a: { n: 9, d: 14 },
    b: { n: 11, d: 18 },
    correctChoice: 'A',
    category: 'unlike_denominator',
    difficulty: 3,
  },
];
